# Setup
title:               Koder's Diary
tagline:             "Thoughts and journey of a coder"
description:         'This blog is a record of all my thoughts and my experiments to improve myself. As there is always room for improvement, there is no end to it. Thus,
  this is called Endless Experiments. This blog revolves around Health, Productivity and Programming.'
url:
baseurl:             ''

permalink:           pretty

# About/contact
author:
  name:              Karthik Sundar
  url:
  email:             karthiksundar30092002@gmail.com

# Gems
plugins:
  - jekyll-feed

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
disqus:
  shortname: gamer-15
export: JEKYLL_ENV=production